/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tjw4g3JnW5W
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Chivo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Separator } from "@/components/ui/separator";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Card, CardContent } from "./ui/card";
import { MapPin } from "lucide-react";
import { CalendarIcon, ClockIcon } from "@radix-ui/react-icons";

export function Checkout() {
  return (
    <div className="relative w-full">
      <div className="absolute top-[-100px] inset-0 z-0 w-full h-full overflow-hidden">
        <img
          src="/test.avif" // Replace with your actual background image path
          alt="Background"
          className="w-full h-full object-cover object-center opacity-40 blur-[50px]"
        />
        <div className="absolute inset-0 bg-gradient-to-b from-transparent to-background opacity-100"></div>
      </div>
      {/* <div className="w-full max-w-4xl mx-auto py-12 md:py-16 px-4 md:px-6"> */}
      <div className="relative z-10 w-full max-w-4xl mx-auto py-12 md:py-16 px-4 md:px-6">
        <div className="grid gap-8 md:gap-12">
          <div className="space-y-6">
            <div className="space-y-2">
              <h1 className="text-2xl font-bold">Acme Music Festival</h1>
              <div className="flex flex-col sm:flex-row sm:items-center gap-2 text-sm text-muted-foreground">
                <div className="flex items-center gap-1">
                  <CalendarIcon className="w-4 h-4" />
                  <span>June 1, 2024</span>
                </div>
                <div className="flex items-center gap-1">
                  <ClockIcon className="w-4 h-4" />
                  <span>7:00 PM - 11:00 PM</span>
                </div>
                <div className="flex items-center gap-1">
                  <MapPin className="w-4 h-4" />
                  <span>Downtown Park, San Francisco</span>
                </div>
              </div>
            </div>
            <Card className="w-full max-w-3xl mx-auto">
              <CardContent className="p-6">
                <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
                  <div className="col-span-1 md:col-span-1">
                    <Label className="mb-2 block text-sm font-medium">
                      Ticket Type
                    </Label>
                    <div className="flex items-center gap-3">
                      <div className="w-4 h-4 rounded-full bg-primary" />
                      <span className="text-base font-medium">
                        General Admission
                      </span>
                    </div>
                  </div>
                  <div>
                    <Label className="mb-2 block text-sm font-medium">
                      Quantity
                    </Label>
                    <div className="text-2xl font-bold">2</div>
                  </div>
                  <div>
                    <Label className="mb-2 block text-sm font-medium">
                      Price per Ticket
                    </Label>
                    <div className="text-2xl font-bold">$50</div>
                  </div>
                  <div>
                    <Label className="mb-2 block text-sm font-medium">
                      Total Ticket Cost
                    </Label>
                    <div className="text-2xl font-bold text-primary">$100</div>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card className="w-full max-w-3xl mx-auto">
              <CardContent className="p-6">
                <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
                  <div className="col-span-1 md:col-span-1">
                    <Label className="mb-2 block text-sm font-medium">
                      Ticket Type
                    </Label>
                    <div className="flex items-center gap-3">
                      <div className="w-4 h-4 rounded-full bg-primary" />
                      <span className="text-base font-medium">
                        General Admission
                      </span>
                    </div>
                  </div>
                  <div>
                    <Label className="mb-2 block text-sm font-medium">
                      Quantity
                    </Label>
                    <div className="text-2xl font-bold">2</div>
                  </div>
                  <div>
                    <Label className="mb-2 block text-sm font-medium">
                      Price per Ticket
                    </Label>
                    <div className="text-2xl font-bold">$50</div>
                  </div>
                  <div>
                    <Label className="mb-2 block text-sm font-medium">
                      Total Ticket Cost
                    </Label>
                    <div className="text-2xl font-bold text-primary">$100</div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
          <div className="grid gap-4">
            <div className="grid grid-cols-2 gap-4">
              <div className="grid gap-2">
                <Label htmlFor="firstName">First Name</Label>
                <Input id="firstName" placeholder="Enter your name" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="lastName">Last Name</Label>
                <Input
                  id="lastName"
                  type="email"
                  placeholder="Enter your email"
                />
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="grid gap-2">
                <Label htmlFor="phone">Phone</Label>
                <Input id="phone" placeholder="Enter your city" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="email">Email</Label>
                <Input id="state" placeholder="Enter your state" />
              </div>
            </div>
          </div>
          <div className="items-top flex gap-2">
            <Checkbox id="terms" />
            <div className="grid gap-1.5 leading-none">
              <Label htmlFor="terms" className="text-sm font-medium">
                I agree to the terms and conditions
              </Label>
              <p className="text-sm text-muted-foreground">
                By checking this box, you agree to our Terms of Service and
                Privacy Policy.
              </p>
            </div>
          </div>
          <div className="grid gap-4">
            <div className="flex items-center justify-between">
              <div>Ticket Cost</div>
              <div className="text-2xl font-bold">$50</div>
            </div>
            <div className="flex items-center justify-between">
              <div>Platform Fee</div>
              <div className="text-2xl font-bold">$5</div>
            </div>
            <div className="flex items-center justify-between">
              <div>Payment Gateway Fee</div>
              <div className="text-2xl font-bold">$2</div>
            </div>
            <div className="flex flex-col sm:flex-row items-center gap-2">
              <Input
                type="text"
                placeholder="Enter coupon code"
                className="w-full sm:w-auto flex-grow"
              />
              <Button variant="outline" className="w-full sm:w-auto">
                Apply
              </Button>
            </div>
            <Separator />
            <div className="flex items-center justify-between">
              <div className="text-lg font-bold">Total</div>
              <div className="text-2xl font-bold">$57</div>
            </div>
          </div>
          <div className="grid gap-4">
            <Button size="lg" className="w-full">
              Complete Purchase
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
