/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/eLtdfZHSMQo
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"

export function EventsList() {
  return (
    <div className="flex flex-col min-h-dvh dark:bg-[url('/pattern.svg')] dark:bg-cover dark:bg-no-repeat dark:bg-center dark:text-foreground">
      <header className="px-4 lg:px-6 h-14 flex items-center justify-between">
        <Link href="#" className="flex items-center" prefetch={false}>
          <MountainIcon className="size-6" />
          <span className="sr-only">Acme Events</span>
        </Link>
        <div className="flex items-center gap-4">
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4 dark:text-primary-foreground"
            prefetch={false}
          >
            Manage Events
          </Link>
          <Avatar className="w-8 h-8">
            <AvatarImage src="/placeholder-user.jpg" />
            <AvatarFallback>JD</AvatarFallback>
          </Avatar>
        </div>
      </header>
      <main className="flex-1 py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6 grid gap-12 justify-center">
          <div className="grid gap-4 text-center">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">
              Discover Upcoming Events
            </h1>
            <p className="max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-muted-foreground">
              Check out the latest events hosted by our community. Discover new experiences and connect with like-minded
              individuals.
            </p>
            <div className="flex items-center justify-center gap-4">
              <Avatar className="w-10 h-10 border">
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>OA</AvatarFallback>
              </Avatar>
              <div className="font-semibold dark:text-foreground">Acme Events</div>
            </div>
          </div>
          <div className="grid gap-6 sm:grid-cols-1 md:grid-cols-1 lg:grid-cols-1">
            <div className="group grid gap-4 bg-muted dark:bg-card dark:text-card-foreground rounded-lg overflow-hidden hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
              <div className="p-4 grid gap-2">
                <div className="flex items-center justify-between">
                  <div className="text-lg font-semibold">
                    Tech Conference 2024
                    <Badge variant="secondary" className="ml-2">
                      New
                    </Badge>
                  </div>
                  <Link href="#" className="text-primary dark:text-primary-foreground" prefetch={false}>
                    <ArrowRightIcon className="w-5 h-5" />
                  </Link>
                </div>
                <div className="flex items-center gap-2 text-sm text-muted-foreground dark:text-muted-foreground">
                  <MapPinIcon className="w-4 h-4" />
                  San Francisco, CA
                </div>
                <div className="flex items-center gap-2 text-sm text-muted-foreground dark:text-muted-foreground">
                  <CalendarIcon className="w-4 h-4" />
                  June 1-3, 2024
                </div>
              </div>
            </div>
            <div className="group grid gap-4 bg-muted dark:bg-card dark:text-card-foreground rounded-lg overflow-hidden hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
              <div className="p-4 grid gap-2">
                <div className="flex items-center justify-between">
                  <div className="text-lg font-semibold">
                    Music Festival 2024
                    <Badge className="ml-2">Popular</Badge>
                  </div>
                  <Link href="#" className="text-primary dark:text-primary-foreground" prefetch={false}>
                    <ArrowRightIcon className="w-5 h-5" />
                  </Link>
                </div>
                <div className="flex items-center gap-2 text-sm text-muted-foreground dark:text-muted-foreground">
                  <MapPinIcon className="w-4 h-4" />
                  New York City, NY
                </div>
                <div className="flex items-center gap-2 text-sm text-muted-foreground dark:text-muted-foreground">
                  <CalendarIcon className="w-4 h-4" />
                  July 15-17, 2024
                </div>
              </div>
            </div>
            <div className="group grid gap-4 bg-muted dark:bg-card dark:text-card-foreground rounded-lg overflow-hidden hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
              <div className="p-4 grid gap-2">
                <div className="flex items-center justify-between">
                  <div className="text-lg font-semibold">Art Showcase 2024</div>
                  <Link href="#" className="text-primary dark:text-primary-foreground" prefetch={false}>
                    <ArrowRightIcon className="w-5 h-5" />
                  </Link>
                </div>
                <div className="flex items-center gap-2 text-sm text-muted-foreground dark:text-muted-foreground">
                  <MapPinIcon className="w-4 h-4" />
                  Chicago, IL
                </div>
                <div className="flex items-center gap-2 text-sm text-muted-foreground dark:text-muted-foreground">
                  <CalendarIcon className="w-4 h-4" />
                  August 20-22, 2024
                </div>
              </div>
            </div>
            <div className="group grid gap-4 bg-muted dark:bg-card dark:text-card-foreground rounded-lg overflow-hidden hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
              <div className="p-4 grid gap-2">
                <div className="flex items-center justify-between">
                  <div className="text-lg font-semibold">Wellness Retreat 2024</div>
                  <Link href="#" className="text-primary dark:text-primary-foreground" prefetch={false}>
                    <ArrowRightIcon className="w-5 h-5" />
                  </Link>
                </div>
                <div className="flex items-center gap-2 text-sm text-muted-foreground dark:text-muted-foreground">
                  <MapPinIcon className="w-4 h-4" />
                  Sedona, AZ
                </div>
                <div className="flex items-center gap-2 text-sm text-muted-foreground dark:text-muted-foreground">
                  <CalendarIcon className="w-4 h-4" />
                  September 5-9, 2024
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t dark:border-t-muted">
        <p className="text-xs text-muted-foreground dark:text-muted-foreground">
          &copy; 2024 Acme Events. All rights reserved.
        </p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link
            href="#"
            className="text-xs hover:underline underline-offset-4 dark:text-muted-foreground"
            prefetch={false}
          >
            Terms of Service
          </Link>
          <Link
            href="#"
            className="text-xs hover:underline underline-offset-4 dark:text-muted-foreground"
            prefetch={false}
          >
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  )
}

function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}


function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function MapPinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z" />
      <circle cx="12" cy="10" r="3" />
    </svg>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
